#' Simulated gut microbiome MAG count table
#'
#' A small, **simulated** example data set representing metagenome-assembled
#' genome (MAG) abundances across host samples from two groups (`control` and
#' `treatment`), where a block of MAGs is enriched in the treatment group so
#' that beta diversity is non-trivial. Generated by `data-raw/make-data.R`.
#'
#' @format An integer matrix with 24 rows (MAGs, `mag01`..`mag24`) and 12
#'   columns (samples, `ctrl01`..`ctrl06` and `trt01`..`trt06`).
#' @seealso [gut_tree], [gut_traits]
#' @examples
#' hilldiv(gut_counts, q = c(0, 1, 2))
"gut_counts"

#' Phylogeny for the simulated gut MAGs
#'
#' An ultrametric coalescent tree over the 24 MAGs in [gut_counts], scaled to
#' unit depth. Use it for the phylogenetic-diversity paths.
#'
#' @format A `phylo` object (see the \pkg{ape} package) with 24 tips whose
#'   labels match the rows of [gut_counts].
#' @seealso [gut_counts], [gut_traits]
#' @examples
#' hilldiv(gut_counts, q = c(0, 1), tree = gut_tree)
"gut_tree"

#' Functional traits for the simulated gut MAGs
#'
#' A trait table for the 24 MAGs in [gut_counts], mixing continuous, categorical
#' and binary traits. Convert it to a functional distance with [traits2dist()]
#' for the functional-diversity paths.
#'
#' @format A data frame with 24 rows (MAGs) and 4 columns:
#' \describe{
#'   \item{genome_size}{Approximate genome size in Mbp (numeric).}
#'   \item{gc_content}{GC content as a proportion (numeric).}
#'   \item{oxygen}{Oxygen tolerance: aerobe, anaerobe or facultative (factor).}
#'   \item{motility}{Motility indicator, 0/1 (integer).}
#' }
#' @seealso [gut_counts], [gut_tree], [traits2dist()]
#' @examples
#' d <- traits2dist(gut_traits)
#' hilldiv(gut_counts, q = c(0, 1), dist = d)
"gut_traits"
